[versions]
agp = "9.0.1"
coroutines = "1.10.2"
dataStore = "1.2.0"
kotlin = "2.3.10"

[libraries]
coroutinesCore = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
preferencesDataStore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
